FROM rust:1.49
WORKDIR app

RUN apt-get update -y \
    && apt-get install -y --no-install-recommends openssl \
    # Clean up
    && apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/*

RUN cargo install cargo-watch
RUN cargo install sqlx-cli
